import type { OnePieceDataBundle } from './types';
import { readFileSync } from 'fs';
import { join } from 'path';

// Read at Next.js SSG build time. The bundle is generated by scripts/build-onepiece.ts.
// Falls back to empty arrays when the bundle hasn't been generated yet.
function loadBundle(): OnePieceDataBundle {
  const bundlePath = join(process.cwd(), 'public/onepiececontent/data/bundle.json');
  try {
    return JSON.parse(readFileSync(bundlePath, 'utf8')) as OnePieceDataBundle;
  } catch {
    return { characters: [], devilFruits: [], crews: [], fetchedAt: '' };
  }
}

export const onePieceData = loadBundle();
