import type { OnePieceDevilFruitRecord } from './types';

function df(
  name: string,
  englishName: string | null,
  type: OnePieceDevilFruitRecord['type'],
  userName: string | null = null,
): OnePieceDevilFruitRecord {
  const id = name.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z0-9-]/g, '');
  return { id, name, englishName, type, userId: null, userName };
}

export const STATIC_DEVIL_FRUITS: OnePieceDevilFruitRecord[] = [
  // === Paramecia ===
  df('Gomu Gomu no Mi', 'Gum-Gum Fruit', 'Zoan', 'Monkey D. Luffy'),
  df('Bara Bara no Mi', 'Chop-Chop Fruit', 'Paramecia', 'Buggy'),
  df('Sube Sube no Mi', 'Slip-Slip Fruit', 'Paramecia', 'Alvida'),
  df('Bomu Bomu no Mi', 'Bomb-Bomb Fruit', 'Paramecia', 'Mr. 5'),
  df('Kiro Kiro no Mi', 'Kilo-Kilo Fruit', 'Paramecia', 'Miss Valentine'),
  df('Hana Hana no Mi', 'Flower-Flower Fruit', 'Paramecia', 'Nico Robin'),
  df('Doru Doru no Mi', 'Wax-Wax Fruit', 'Paramecia', 'Galdino'),
  df('Baku Baku no Mi', 'Munch-Munch Fruit', 'Paramecia', 'Wapol'),
  df('Mane Mane no Mi', 'Clone-Clone Fruit', 'Paramecia', 'Bentham'),
  df('Supa Supa no Mi', 'Dice-Dice Fruit', 'Paramecia', 'Daz Bones'),
  df('Toge Toge no Mi', 'Spike-Spike Fruit', 'Paramecia', 'Zala'),
  df('Ori Ori no Mi', 'Bind-Bind Fruit', 'Paramecia', 'Hina'),
  df('Bane Bane no Mi', 'Spring-Spring Fruit', 'Paramecia', 'Bellamy'),
  df('Noro Noro no Mi', 'Slow-Slow Fruit', 'Paramecia', 'Foxy'),
  df('Doa Doa no Mi', 'Door-Door Fruit', 'Paramecia', 'Blueno'),
  df('Awa Awa no Mi', 'Bubble-Bubble Fruit', 'Paramecia', 'Kalifa'),
  df('Yomi Yomi no Mi', 'Revive-Revive Fruit', 'Paramecia', 'Brook'),
  df('Kage Kage no Mi', 'Shadow-Shadow Fruit', 'Paramecia', 'Gecko Moria'),
  df('Horo Horo no Mi', 'Hollow-Hollow Fruit', 'Paramecia', 'Perona'),
  df('Suke Suke no Mi', 'Clear-Clear Fruit', 'Paramecia', 'Absalom'),
  df('Nikyu Nikyu no Mi', 'Paw-Paw Fruit', 'Paramecia', 'Bartholomew Kuma'),
  df('Mero Mero no Mi', 'Love-Love Fruit', 'Paramecia', 'Boa Hancock'),
  df('Doku Doku no Mi', 'Venom-Venom Fruit', 'Paramecia', 'Magellan'),
  df('Gura Gura no Mi', 'Tremor-Tremor Fruit', 'Paramecia', 'Edward Newgate'),
  df('Fuwa Fuwa no Mi', 'Float-Float Fruit', 'Paramecia', 'Shiki'),
  df('Ito Ito no Mi', 'String-String Fruit', 'Paramecia', 'Donquixote Doflamingo'),
  df('Ope Ope no Mi', 'Op-Op Fruit', 'Paramecia', 'Trafalgar Law'),
  df('Hobi Hobi no Mi', 'Hobby-Hobby Fruit', 'Paramecia', 'Sugar'),
  df('Bari Bari no Mi', 'Barrier-Barrier Fruit', 'Paramecia', 'Bartolomeo'),
  df('Nui Nui no Mi', 'Stitch-Stitch Fruit', 'Paramecia', 'Leo'),
  df('Guru Guru no Mi', 'Spin-Spin Fruit', 'Paramecia', 'Buffalo'),
  df('Jake Jake no Mi', 'Jacket-Jacket Fruit', 'Paramecia', 'Kelly Funk'),
  df('Pamu Pamu no Mi', 'Pop-Pop Fruit', 'Paramecia', 'Gladius'),
  df('Kira Kira no Mi', 'Glitter-Glitter Fruit', 'Paramecia', 'Jozu'),
  df('Woshu Woshu no Mi', 'Wash-Wash Fruit', 'Paramecia', 'Tsuru'),
  df('Chiyu Chiyu no Mi', 'Heal-Heal Fruit', 'Paramecia', 'Mansherry'),
  df('Shiro Shiro no Mi', 'Castle-Castle Fruit', 'Paramecia', 'Capone Bege'),
  df('Zushi Zushi no Mi', 'Press-Press Fruit', 'Paramecia', 'Issho'),
  df('Nagi Nagi no Mi', 'Calm-Calm Fruit', 'Paramecia', 'Donquixote Rosinante'),
  df('Soru Soru no Mi', 'Soul-Soul Fruit', 'Paramecia', 'Charlotte Linlin'),
  df('Mochi Mochi no Mi', 'Mochi-Mochi Fruit', 'Paramecia', 'Charlotte Katakuri'),
  df('Shibo Shibo no Mi', 'Wring-Wring Fruit', 'Paramecia', 'Charlotte Smoothie'),
  df('Pero Pero no Mi', 'Candy-Candy Fruit', 'Paramecia', 'Charlotte Perospero'),
  df('Bisu Bisu no Mi', 'Biscuit-Biscuit Fruit', 'Paramecia', 'Charlotte Cracker'),
  df('Mira Mira no Mi', 'Mirror-Mirror Fruit', 'Paramecia', 'Charlotte Brulee'),
  df('Netsu Netsu no Mi', 'Heat-Heat Fruit', 'Paramecia', 'Charlotte Oven'),
  df('Toki Toki no Mi', 'Time-Time Fruit', 'Paramecia', 'Kozuki Toki'),
  df('Horu Horu no Mi', 'Horm-Horm Fruit', 'Paramecia', 'Emporio Ivankov'),
  df('Choki Choki no Mi', 'Snip-Snip Fruit', 'Paramecia', 'Inazuma'),
  df('Wara Wara no Mi', 'Straw-Straw Fruit', 'Paramecia', 'Basil Hawkins'),
  df('Memo Memo no Mi', 'Memo-Memo Fruit', 'Paramecia', "Charlotte Mont-d'Or"),
  df('Tama Tama no Mi', 'Egg-Egg Fruit', 'Paramecia', 'Charlotte Tamago'),
  df('Oshi Oshi no Mi', 'Push-Push Fruit', 'Paramecia', 'Lindbergh'),
  df('Omo Omo no Mi', 'Omo-Omo Fruit', 'Paramecia', 'Magellan'),
  // === Logia ===
  df('Mera Mera no Mi', 'Flame-Flame Fruit', 'Logia', 'Portgas D. Ace'),
  df('Yami Yami no Mi', 'Dark-Dark Fruit', 'Logia', 'Marshall D. Teach'),
  df('Hie Hie no Mi', 'Ice-Ice Fruit', 'Logia', 'Kuzan'),
  df('Pika Pika no Mi', 'Glint-Glint Fruit', 'Logia', 'Borsalino'),
  df('Magu Magu no Mi', 'Magma-Magma Fruit', 'Logia', 'Sakazuki'),
  df('Goro Goro no Mi', 'Rumble-Rumble Fruit', 'Logia', 'Enel'),
  df('Moku Moku no Mi', 'Plume-Plume Fruit', 'Logia', 'Smoker'),
  df('Suna Suna no Mi', 'Sand-Sand Fruit', 'Logia', 'Crocodile'),
  df('Numa Numa no Mi', 'Swamp-Swamp Fruit', 'Logia', 'Caribou'),
  df('Gasu Gasu no Mi', 'Gas-Gas Fruit', 'Logia', 'Caesar Clown'),
  df('Yuki Yuki no Mi', 'Snow-Snow Fruit', 'Logia', 'Monet'),
  // === Zoan ===
  df('Hito Hito no Mi', 'Human-Human Fruit', 'Zoan', 'Tony Tony Chopper'),
  df('Hito Hito no Mi: Model Daibutsu', 'Human-Human Fruit: Model Daibutsu', 'Zoan', 'Sengoku'),
  df('Hito Hito no Mi: Model Nika', 'Human-Human Fruit: Sun God Nika', 'Zoan', 'Monkey D. Luffy'),
  df('Inu Inu no Mi: Model Jackal', 'Dog-Dog Fruit: Model Jackal', 'Zoan', 'Chaka'),
  df('Inu Inu no Mi: Model Wolf', 'Dog-Dog Fruit: Model Wolf', 'Zoan', 'Jabra'),
  df('Inu Inu no Mi: Model Okuchi no Makami', 'Dog-Dog Fruit: Okuchi no Makami', 'Zoan', 'Yamato'),
  df('Inu Inu no Mi: Model Kyubi no Kitsune', 'Dog-Dog Fruit: Nine-Tailed Fox', 'Zoan', 'Catarina Devon'),
  df('Neko Neko no Mi: Model Leopard', 'Cat-Cat Fruit: Model Leopard', 'Zoan', 'Rob Lucci'),
  df('Neko Neko no Mi: Model Saber-toothed Tiger', 'Cat-Cat Fruit: Saber-toothed Tiger', 'Zoan', 'Page One'),
  df('Tori Tori no Mi: Model Eagle', 'Bird-Bird Fruit: Model Eagle', 'Zoan', 'Pell'),
  df('Tori Tori no Mi: Model Phoenix', 'Bird-Bird Fruit: Model Phoenix', 'Zoan', 'Marco'),
  df('Tori Tori no Mi: Model Albatross', 'Bird-Bird Fruit: Model Albatross', 'Zoan', 'Morgans'),
  df('Hebi Hebi no Mi: Model Anaconda', 'Snake-Snake Fruit: Model Anaconda', 'Zoan', 'Boa Sandersonia'),
  df('Hebi Hebi no Mi: Model King Cobra', 'Snake-Snake Fruit: Model King Cobra', 'Zoan', 'Boa Marigold'),
  df('Uma Uma no Mi', 'Horse-Horse Fruit', 'Zoan', 'Stronger'),
  df('Mogu Mogu no Mi', 'Mole-Mole Fruit', 'Zoan', 'Miss Merry Christmas'),
  df('Sara Sara no Mi: Model Axolotl', 'Sala-Sala Fruit: Model Axolotl', 'Zoan', 'Smiley'),
  df('Ryu Ryu no Mi: Model Allosaurus', 'Dragon-Dragon Fruit: Model Allosaurus', 'Zoan', 'X Drake'),
  df('Ryu Ryu no Mi: Model Pteranodon', 'Dragon-Dragon Fruit: Model Pteranodon', 'Zoan', 'King'),
  df('Ryu Ryu no Mi: Model Brachiosaurus', 'Dragon-Dragon Fruit: Model Brachiosaurus', 'Zoan', 'Queen'),
  df('Ryu Ryu no Mi: Model Spinosaurus', 'Dragon-Dragon Fruit: Model Spinosaurus', 'Zoan', 'Sasaki'),
  df('Ryu Ryu no Mi: Model Triceratops', 'Dragon-Dragon Fruit: Model Triceratops', 'Zoan', 'Sasaki'),
  df('Ryu Ryu no Mi: Model Pachycephalosaurus', 'Dragon-Dragon Fruit: Model Pachycephalosaurus', 'Zoan', 'Ulti'),
  df('Uo Uo no Mi: Model Seiryu', 'Fish-Fish Fruit: Model Azure Dragon', 'Zoan', 'Kaido'),
  df('Zou Zou no Mi: Model Mammoth', 'Elephant-Elephant Fruit: Model Mammoth', 'Zoan', 'Jack'),
  df('Batto Batto no Mi: Model Vampire', 'Bat-Bat Fruit: Model Vampire', 'Zoan', 'Patrick Redfield'),
];
