// Auto-generated by scripts/scrape-origins.ts — do not edit by hand.
// Keys: normalizeName(character.name) — lowercase, no punctuation, collapsed spaces.
// Values: sea of origin or island/region as shown on the One Piece wiki.
export const STATIC_ORIGINS: Record<string, string> = {};
