// Auto-generated by scripts/scrape-wiki-meta.ts — do not edit by hand.
// Keys: normalizeName(character.name). Values: "Male" or "Female" from the One Piece wiki.
export const STATIC_WIKI_GENDERS: Record<string, string> = {
};
