import type { DevilFruitType, HakiType } from './types';

type StaticCharData = {
  affiliation?: string[];
  devilFruit?: string | null;
  devilFruitEnglish?: string | null;
  devilFruitType?: DevilFruitType | null;
  status?: 'Alive' | 'Deceased' | null;
  position?: string | null;
  gender?: 'Male' | 'Female' | 'Unknown' | null;
  haki?: HakiType[];
  firstArc?: string | null;
};

// Codex-verified overrides for the top characters by favorites.
// Keys are normalized via normalizeName() (lowercase, strip punctuation, collapse spaces).
// Undefined = leave bundle value unchanged. Explicit null = clear the field.
export const STATIC_CHARACTER_DATA: Record<string, StaticCharData> = {
  // ── Straw Hat Pirates ────────────────────────────────────────────────────
  'monkey d luffy': {
    affiliation: ['Straw Hat Pirates'],
    // True name revealed Ch. 1044; was called Gomu Gomu no Mi for 1000+ chapters
    devilFruit: 'Hito Hito no Mi, Model: Nika',
    devilFruitEnglish: 'Human-Human Fruit, Model: Nika',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Romance Dawn',
  },
  'roronoa zoro': {
    affiliation: ['Straw Hat Pirates'],
    status: 'Alive',
    position: 'Swordsman',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Romance Dawn',
  },
  'sanji': {
    affiliation: ['Straw Hat Pirates'],
    status: 'Alive',
    position: 'Cook',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Baratie',
  },
  'nico robin': {
    affiliation: ['Straw Hat Pirates'],
    devilFruit: 'Hana Hana no Mi',
    devilFruitEnglish: 'Flower-Flower Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Archaeologist',
    gender: 'Female',
    haki: ['Armament', 'Observation'],
    firstArc: 'Whisky Peak',
  },
  'trafalgar law': {
    affiliation: ['Heart Pirates'],
    devilFruit: 'Ope Ope no Mi',
    devilFruitEnglish: 'Op-Op Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Sabaody Archipelago',
  },
  'tony tony chopper': {
    affiliation: ['Straw Hat Pirates'],
    devilFruit: 'Hito Hito no Mi',
    devilFruitEnglish: 'Human-Human Fruit',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Doctor',
    gender: 'Male',
    haki: [],
    firstArc: 'Drum Island',
  },
  'nami': {
    affiliation: ['Straw Hat Pirates'],
    status: 'Alive',
    position: 'Navigator',
    gender: 'Female',
    haki: [],
    firstArc: 'Orange Town',
  },
  'usopp': {
    affiliation: ['Straw Hat Pirates'],
    status: 'Alive',
    position: 'Sniper',
    gender: 'Male',
    haki: [],
    firstArc: 'Syrup Village',
  },
  'portgas d ace': {
    affiliation: ['Whitebeard Pirates'],
    devilFruit: 'Mera Mera no Mi',
    devilFruitEnglish: 'Flame-Flame Fruit',
    devilFruitType: 'Logia',
    status: 'Deceased',
    position: '2nd Division Commander',
    gender: 'Male',
    haki: ['Armament', 'Conqueror'],
    firstArc: 'Drum Island',
  },
  'brook': {
    affiliation: ['Straw Hat Pirates'],
    devilFruit: 'Yomi Yomi no Mi',
    devilFruitEnglish: 'Revive-Revive Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Musician',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Thriller Bark',
  },
  'franky': {
    affiliation: ['Straw Hat Pirates'],
    status: 'Alive',
    position: 'Shipwright',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Water 7',
  },
  'jinbe': {
    affiliation: ['Straw Hat Pirates'],
    status: 'Alive',
    position: 'Helmsman',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Marineford',
  },

  // ── Yonko / Emperor-class ────────────────────────────────────────────────
  'shanks': {
    affiliation: ['Red Hair Pirates'],
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Romance Dawn',
  },
  'edward newgate': {
    affiliation: ['Whitebeard Pirates'],
    devilFruit: 'Gura Gura no Mi',
    devilFruitEnglish: 'Tremor-Tremor Fruit',
    devilFruitType: 'Paramecia',
    status: 'Deceased',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Marineford',
  },
  'charlotte linlin': {
    affiliation: ['Big Mom Pirates'],
    devilFruit: 'Soru Soru no Mi',
    devilFruitEnglish: 'Soul-Soul Fruit',
    devilFruitType: 'Paramecia',
    position: 'Captain',
    gender: 'Female',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Whole Cake Island',
  },
  'kaidou': {
    affiliation: ['Beasts Pirates'],
    devilFruit: 'Uo Uo no Mi, Model: Seiryu',
    devilFruitEnglish: 'Fish-Fish Fruit, Model: Azure Dragon',
    devilFruitType: 'Zoan',
    position: 'Governor-General',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Wano',
  },
  'marshall d teach': {
    affiliation: ['Blackbeard Pirates'],
    // Unique: holds two devil fruits
    devilFruit: 'Yami Yami no Mi / Gura Gura no Mi',
    devilFruitEnglish: 'Dark-Dark Fruit / Tremor-Tremor Fruit',
    devilFruitType: null,
    status: 'Alive',
    position: 'Admiral',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Jaya',
  },
  'buggy': {
    affiliation: ['Cross Guild'],
    devilFruit: 'Bara Bara no Mi',
    devilFruitEnglish: 'Chop-Chop Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Emperor',
    gender: 'Male',
    haki: [],
    firstArc: 'Orange Town',
  },

  // ── Warlords / Shichibukai ────────────────────────────────────────────────
  'dracule mihawk': {
    affiliation: ['Cross Guild'],
    status: 'Alive',
    position: 'Co-Founder',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Baratie',
  },
  'donquixote doflamingo': {
    affiliation: ['Donquixote Pirates'],
    devilFruit: 'Ito Ito no Mi',
    devilFruitEnglish: 'String-String Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Marineford',
  },
  'boa hancock': {
    affiliation: ['Kuja Pirates'],
    devilFruit: 'Mero Mero no Mi',
    devilFruitEnglish: 'Love-Love Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Captain',
    gender: 'Female',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Amazon Lily',
  },
  'crocodile': {
    affiliation: ['Cross Guild'],
    devilFruit: 'Suna Suna no Mi',
    devilFruitEnglish: 'Sand-Sand Fruit',
    devilFruitType: 'Logia',
    status: 'Alive',
    position: 'Officer',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Alabasta',
  },
  'bartholomew kuma': {
    affiliation: ['Revolutionary Army'],
    devilFruit: 'Nikyu Nikyu no Mi',
    devilFruitEnglish: 'Paw-Paw Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Army Commander',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Thriller Bark',
  },
  'gecko moria': {
    affiliation: ['Thriller Bark Pirates'],
    devilFruit: 'Kage Kage no Mi',
    devilFruitEnglish: 'Shadow-Shadow Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: [],
    firstArc: 'Thriller Bark',
  },

  // ── Charlotte (Big Mom) Family ────────────────────────────────────────────
  'charlotte katakuri': {
    affiliation: ['Big Mom Pirates'],
    devilFruit: 'Mochi Mochi no Mi',
    devilFruitEnglish: 'Mochi-Mochi Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Sweet Commander',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Whole Cake Island',
  },
  'charlotte pudding': {
    affiliation: ['Big Mom Pirates'],
    devilFruit: 'Memo Memo no Mi',
    devilFruitEnglish: 'Memo-Memo Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Minister of Chocolate',
    gender: 'Female',
    haki: [],
    firstArc: 'Whole Cake Island',
  },

  // ── Revolutionary Army ────────────────────────────────────────────────────
  'sabo': {
    affiliation: ['Revolutionary Army'],
    devilFruit: 'Mera Mera no Mi',
    devilFruitEnglish: 'Flame-Flame Fruit',
    devilFruitType: 'Logia',
    status: 'Alive',
    position: 'Chief of Staff',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Post-War',
  },
  'monkey d dragon': {
    affiliation: ['Revolutionary Army'],
    status: 'Alive',
    position: 'Supreme Commander',
    gender: 'Male',
    haki: [],
    firstArc: 'Loguetown',
  },
  'emporio ivankov': {
    affiliation: ['Revolutionary Army'],
    devilFruit: 'Horu Horu no Mi',
    devilFruitEnglish: 'Horm-Horm Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Commander',
    gender: 'Male',
    haki: [],
    firstArc: 'Impel Down',
  },
  'koala': {
    affiliation: ['Revolutionary Army'],
    status: 'Alive',
    position: 'Officer',
    gender: 'Female',
    haki: [],
    firstArc: 'Dressrosa',
  },

  // ── Marines / World Government ────────────────────────────────────────────
  'monkey d garp': {
    affiliation: ['Marines'],
    status: 'Alive',
    position: 'Vice Admiral',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Water 7',
  },
  'sengoku': {
    affiliation: ['Marines'],
    devilFruit: 'Hito Hito no Mi, Model: Daibutsu',
    devilFruitEnglish: 'Human-Human Fruit, Model: Buddha',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Inspector General',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Marineford',
  },
  'sakazuki': {
    affiliation: ['Marines'],
    devilFruit: 'Magu Magu no Mi',
    devilFruitEnglish: 'Mag-Mag Fruit',
    devilFruitType: 'Logia',
    status: 'Alive',
    position: 'Fleet Admiral',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Marineford',
  },
  'kuzan': {
    affiliation: ['Blackbeard Pirates'],
    devilFruit: 'Hie Hie no Mi',
    devilFruitEnglish: 'Chilly-Chilly Fruit',
    devilFruitType: 'Logia',
    status: 'Alive',
    position: 'Titanic Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Long Ring Long Land',
  },
  'borsalino': {
    affiliation: ['Marines'],
    devilFruit: 'Pika Pika no Mi',
    devilFruitEnglish: 'Glint-Glint Fruit',
    devilFruitType: 'Logia',
    status: 'Alive',
    position: 'Admiral',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Sabaody Archipelago',
  },
  'isshou': {
    affiliation: ['Marines'],
    devilFruit: 'Zushi Zushi no Mi',
    devilFruitEnglish: 'Press-Press Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Admiral',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Dressrosa',
  },
  'smoker': {
    affiliation: ['Marines'],
    devilFruit: 'Moku Moku no Mi',
    devilFruitEnglish: 'Plume-Plume Fruit',
    devilFruitType: 'Logia',
    status: 'Alive',
    position: 'Vice Admiral',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Loguetown',
  },
  'koby': {
    affiliation: ['Marines'],
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Romance Dawn',
  },
  'tashigi': {
    affiliation: ['Marines'],
    status: 'Alive',
    position: 'Captain',
    gender: 'Female',
    haki: ['Armament'],
    firstArc: 'Loguetown',
  },
  'rob lucci': {
    affiliation: ['CP0'],
    devilFruit: 'Neko Neko no Mi, Model: Leopard',
    devilFruitEnglish: 'Cat-Cat Fruit, Model: Leopard',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Agent',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Water 7',
  },
  'magellan': {
    affiliation: ['Impel Down'],
    devilFruit: 'Doku Doku no Mi',
    devilFruitEnglish: 'Venom-Venom Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Vice Warden',
    gender: 'Male',
    haki: [],
    firstArc: 'Impel Down',
  },
  'kaku': {
    affiliation: ['CP0'],
    devilFruit: 'Ushi Ushi no Mi, Model: Giraffe',
    devilFruitEnglish: 'Ox-Ox Fruit, Model: Giraffe',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Agent',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Water 7',
  },

  // ── Donquixote Pirates ────────────────────────────────────────────────────
  'donquixote rosinante': {
    affiliation: ['Marines'],   // undercover Marine; formerly Donquixote Pirates
    devilFruit: 'Nagi Nagi no Mi',
    devilFruitEnglish: 'Calm-Calm Fruit',
    devilFruitType: 'Paramecia',
    status: 'Deceased',
    position: 'Commander',
    gender: 'Male',
    haki: [],
    firstArc: 'Dressrosa',
  },
  'monet': {
    affiliation: ['Donquixote Pirates'],
    devilFruit: 'Yuki Yuki no Mi',
    devilFruitEnglish: 'Snow-Snow Fruit',
    devilFruitType: 'Logia',
    status: 'Deceased',
    position: 'Officer',
    gender: 'Female',
    haki: [],
    firstArc: 'Punk Hazard',
  },
  'senor pink': {
    affiliation: ['Donquixote Pirates'],
    devilFruit: 'Sui Sui no Mi',
    devilFruitEnglish: 'Swim-Swim Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Officer',
    gender: 'Male',
    haki: [],
    firstArc: 'Dressrosa',
  },

  // ── Beasts Pirates ────────────────────────────────────────────────────────
  'yamato': {
    affiliation: ['Wano Country'],
    devilFruit: 'Inu Inu no Mi, Model: Okuchi no Makami',
    devilFruitEnglish: 'Dog-Dog Fruit, Model: Okuchi no Makami',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Guardian Deity',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Wano',
  },
  'ulti': {
    affiliation: ['Beasts Pirates'],
    devilFruit: 'Ryu Ryu no Mi, Model: Pachycephalosaurus',
    devilFruitEnglish: 'Dragon-Dragon Fruit, Model: Pachycephalosaurus',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Tobiroppo',
    gender: 'Female',
    haki: ['Armament'],
    firstArc: 'Wano',
  },
  'king': {
    affiliation: ['Beasts Pirates'],
    devilFruit: 'Ryu Ryu no Mi, Model: Pteranodon',
    devilFruitEnglish: 'Dragon-Dragon Fruit, Model: Pteranodon',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'All-Star',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Wano',
  },

  // ── Heart Pirates ─────────────────────────────────────────────────────────
  'bepo': {
    affiliation: ['Heart Pirates'],
    status: 'Alive',
    position: 'Navigator',
    gender: 'Male',
    haki: [],
    firstArc: 'Sabaody Archipelago',
  },

  // ── Kid Pirates ───────────────────────────────────────────────────────────
  'eustass kid': {
    affiliation: ['Kid Pirates'],
    devilFruit: 'Jiki Jiki no Mi',
    devilFruitEnglish: 'Magnet-Magnet Fruit',
    devilFruitType: 'Paramecia',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Conqueror'],
    firstArc: 'Sabaody Archipelago',
  },
  'killer': {
    affiliation: ['Kid Pirates'],
    status: 'Alive',
    position: 'Combatant',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Sabaody Archipelago',
  },

  // ── Beautiful Pirates / Grand Fleet ──────────────────────────────────────
  'cavendish': {
    affiliation: ['Beautiful Pirates'],
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Dressrosa',
  },
  'bartolomeo': {
    affiliation: ['Barto Club'],
    devilFruit: 'Bari Bari no Mi',
    devilFruitEnglish: 'Barrier-Barrier Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: [],
    firstArc: 'Dressrosa',
  },

  // ── Perona / Misc ─────────────────────────────────────────────────────────
  'perona': {
    devilFruit: 'Horo Horo no Mi',
    devilFruitEnglish: 'Hollow-Hollow Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    gender: 'Female',
    haki: [],
    firstArc: 'Thriller Bark',
  },
  'bentham': {
    affiliation: ['Newkama Land'],
    devilFruit: 'Mane Mane no Mi',
    devilFruitEnglish: 'Clone-Clone Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Queen',
    gender: 'Male',
    haki: [],
    firstArc: 'Alabasta',
  },
  'enel': {
    devilFruit: 'Goro Goro no Mi',
    devilFruitEnglish: 'Rumble-Rumble Fruit',
    devilFruitType: 'Logia',
    status: 'Alive',
    position: 'Leader',
    gender: 'Male',
    haki: ['Observation'],
    firstArc: 'Skypiea',
  },

  // ── Roger Pirates / Legends ───────────────────────────────────────────────
  'gol d roger': {
    status: 'Deceased',
    position: 'Captain',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Romance Dawn',
  },
  'silvers rayleigh': {
    status: 'Alive',
    position: 'Coating Mechanic',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Sabaody Archipelago',
  },
  'kozuki oden': {
    status: 'Deceased',
    position: 'Daimyo',
    gender: 'Male',
    haki: ['Armament', 'Observation', 'Conqueror'],
    firstArc: 'Wano',
  },
  'rocks d xebec': {
    status: 'Deceased',
    position: 'Captain',
    gender: 'Male',
    haki: ['Conqueror'],
    firstArc: 'Marineford',
  },

  // ── Whitebeard Pirates ────────────────────────────────────────────────────
  'marco': {
    affiliation: ['Whitebeard Pirates'],
    devilFruit: 'Tori Tori no Mi, Model: Phoenix',
    devilFruitEnglish: 'Bird-Bird Fruit, Model: Phoenix',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Doctor',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Marineford',
  },

  // ── Bonney Pirates ────────────────────────────────────────────────────────
  'jewelry bonney': {
    affiliation: ['Bonney Pirates'],
    devilFruit: 'Toshi Toshi no Mi',
    devilFruitEnglish: 'Age-Age Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Captain',
    gender: 'Female',
    haki: [],
    firstArc: 'Sabaody Archipelago',
  },

  // ── Vinsmoke / Germa 66 ───────────────────────────────────────────────────
  'vinsmoke reiju': {
    affiliation: ['Germa 66'],
    status: 'Alive',
    position: 'Princess',
    gender: 'Female',
    haki: ['Armament'],
    firstArc: 'Whole Cake Island',
  },

  // ── Wano / Nine Red Scabbards ─────────────────────────────────────────────
  'kinemon': {
    affiliation: ['Nine Red Scabbards'],
    devilFruit: 'Fuku Fuku no Mi',
    devilFruitEnglish: 'Garb-Garb Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Leader of the Nine Red Scabbards',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Punk Hazard',
  },
  'nekomamushi': {
    affiliation: ['Nine Red Scabbards'],
    status: 'Alive',
    position: 'Retainer',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Zou',
  },
  'okiku': {
    affiliation: ['Kozuki Family'],
    status: 'Alive',
    position: 'Retainer',
    gender: 'Female',
    haki: [],
    firstArc: 'Wano',
  },

  // ── Other notable characters ──────────────────────────────────────────────
  'nefertari vivi': {
    affiliation: ['Arabasta Kingdom'],
    status: 'Alive',
    position: 'Princess',
    gender: 'Female',
    haki: [],
    firstArc: 'Whisky Peak',
  },
  'carrot': {
    affiliation: ['Mokomo Dukedom'],
    status: 'Alive',
    position: 'Ruler',
    gender: 'Female',
    haki: [],
    firstArc: 'Zou',
  },
  'shirahoshi': {
    affiliation: ['Ryugu Kingdom'],
    status: 'Alive',
    position: 'Princess',
    gender: 'Female',
    haki: ['Observation'],
    firstArc: 'Fishman Island',
  },
  'loki': {
    affiliation: ['Elbaf'],
    status: 'Alive',
    position: 'Prince',
    gender: 'Male',
    haki: [],
    firstArc: 'Egghead',
  },
  'uta': {
    devilFruit: 'Uta Uta no Mi',
    devilFruitEnglish: 'Sing-Sing Fruit',
    devilFruitType: 'Paramecia',
    position: 'Singer',
    gender: 'Female',
    haki: [],
    firstArc: 'Film Red',
  },
  'imu': {
    affiliation: ['World Government'],
    status: 'Alive',
    position: 'King of the World',
    gender: 'Unknown',
    haki: [],
    firstArc: 'Reverie',
  },
  // Caesar Clown — bundle stores name as "Clown, Caesar" → key "clown caesar"
  'clown caesar': {
    affiliation: ['Neo MADS'],
    devilFruit: 'Gasu Gasu no Mi',
    devilFruitEnglish: 'Gas-Gas Fruit',
    devilFruitType: 'Logia',
    status: 'Alive',
    position: 'Scientist',
    gender: 'Male',
    haki: [],
    firstArc: 'Punk Hazard',
  },
  'pell': {
    affiliation: ['Arabasta Kingdom'],
    devilFruit: 'Tori Tori no Mi, Model: Falcon',
    devilFruitEnglish: 'Bird-Bird Fruit, Model: Falcon',
    devilFruitType: 'Zoan',
    status: 'Alive',
    position: 'Commander of the Royal Guards',
    gender: 'Male',
    haki: [],
    firstArc: 'Alabasta',
  },
  'arlong': {
    affiliation: ['Arlong Pirates'],
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: [],
    firstArc: 'Arlong Park',
  },
  'baby 5': {
    affiliation: ['Happo Navy'],
    devilFruit: 'Buki Buki no Mi',
    devilFruitEnglish: 'Arms-Arms Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    gender: 'Female',
    haki: [],
    firstArc: 'Punk Hazard',
  },
  'foxy': {
    affiliation: ['Foxy Pirates'],
    devilFruit: 'Noro Noro no Mi',
    devilFruitEnglish: 'Slow-Slow Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: [],
    firstArc: 'Long Ring Long Land',
  },
  'otama': {
    affiliation: ['Wano Country'],
    devilFruit: 'Kibi Kibi no Mi',
    devilFruitEnglish: 'Millet-Millet Fruit',
    devilFruitType: 'Paramecia',
    status: 'Alive',
    gender: 'Female',
    haki: [],
    firstArc: 'Wano',
  },
  'benn beckman': {
    affiliation: ['Red Hair Pirates'],
    status: 'Alive',
    position: 'First Mate',
    gender: 'Male',
    haki: ['Armament', 'Observation'],
    firstArc: 'Romance Dawn',
  },
  // Deceased characters
  'hiluluk': {
    status: 'Deceased',
    position: 'Doctor',
    gender: 'Male',
    haki: [],
    firstArc: 'Drum Island',
  },
  'bellemere': {
    affiliation: ['Marines'],
    status: 'Deceased',
    position: 'Former Marine',
    gender: 'Female',
    haki: [],
    firstArc: 'Arlong Park',
  },
  'shimotsuki ryuuma': {
    status: 'Deceased',
    position: 'Samurai',
    gender: 'Male',
    haki: [],
    firstArc: 'Thriller Bark',
  },
  'fisher tiger': {
    affiliation: ['Sun Pirates'],
    status: 'Deceased',
    position: 'Captain',
    gender: 'Male',
    haki: [],
    firstArc: 'Fishman Island',
  },
  'pedro': {
    status: 'Deceased',
    position: 'Captain of the Guardians',
    gender: 'Male',
    haki: [],
    firstArc: 'Zou',
  },
  // Other
  'kyros': {
    affiliation: ['Dressrosa Kingdom'],
    status: 'Alive',
    position: 'Gladiator',
    gender: 'Male',
    haki: ['Armament'],
    firstArc: 'Dressrosa',
  },
  'rebecca': {
    affiliation: ['Dressrosa'],
    status: 'Alive',
    position: 'Lady-in-waiting',
    gender: 'Female',
    haki: [],
    firstArc: 'Dressrosa',
  },
  // ── Giants ────────────────────────────────────────────────────────────────
  'dorry': {
    affiliation: ['Giant Warrior Pirates'],
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: [],
    // firstArc derived from firstAppearance (Chapter 116 → Little Garden)
  },
  'brogy': {
    affiliation: ['Giant Warrior Pirates'],
    status: 'Alive',
    position: 'Captain',
    gender: 'Male',
    haki: [],
    // firstArc derived from firstAppearance
  },
  // ── Drum Island / Sakura Kingdom ──────────────────────────────────────────
  'kureha': {
    affiliation: ['Sakura Kingdom'],
    status: 'Alive',
    position: 'Doctor',
    gender: 'Female',
    haki: [],
    // firstArc derived from firstAppearance (Chapter 134 → Drum Island)
  },

  // ── Gender fills: characters with affil+firstArc in bundle but missing gender ──
  // Sorted alphabetically for maintainability.
  'alvida': { gender: 'Female' },
  'aramaki': { gender: 'Male' },
  'bellamy': { gender: 'Male' },
  'capone bege': { gender: 'Male' },            // MAL: "Capone, Bege"
  'black maria': { gender: 'Female' },
  'blueno': { gender: 'Male' },
  'bonez daz': { gender: 'Male', affiliation: ['Cross Guild'], firstArc: 'Alabasta' },  // MAL: "Bonez, Daz"
  'burgess jesus': { gender: 'Male' },          // MAL: "Burgess, Jesus"
  'camie': { gender: 'Female' },
  'caribou': { gender: 'Male' },
  'charlotte brulee': { gender: 'Female', affiliation: ['Big Mom Pirates'], firstArc: 'Whole Cake Island' },
  'charlotte chiffon': { gender: 'Female' },
  'charlotte mont d or': { gender: 'Male', affiliation: ['Big Mom Pirates'], firstArc: 'Whole Cake Island' },  // "Mont-d'Or"
  'charlotte perospero': { gender: 'Male' },
  'charlotte smoothie': { gender: 'Female' },
  'coby': { gender: 'Male' },                   // alternate romanization for Koby
  'denjiro': { gender: 'Male', affiliation: ['Kozuki Family'], firstArc: 'Wano' },
  'diamante': { gender: 'Male' },
  'galdino': { gender: 'Male', affiliation: ['Cross Guild'], firstArc: 'Little Garden' },
  'gin': { gender: 'Male' },
  'hatchan': { gender: 'Male' },
  'hogback': { gender: 'Male' },
  'hody jones': { gender: 'Male', affiliation: ['New Fish-Man Pirates'], firstArc: 'Fishman Island' },
  'iceburg': { gender: 'Male' },
  'inuarashi': { gender: 'Male' },
  'izou': { gender: 'Male' },
  'jabra': { gender: 'Male' },                  // alternate romanization
  'jabura': { gender: 'Male' },                 // MAL romanization
  'jones hody': { gender: 'Male', affiliation: ['New Fish-Man Pirates'], firstArc: 'Fishman Island' },  // MAL: "Jones, Hody"
  'kalifa': { gender: 'Female' },
  'karasu': { gender: 'Male' },
  'kawamatsu': { gender: 'Male' },
  'kaya': { gender: 'Female', affiliation: ['Syrup Village'], firstArc: 'Syrup Village' },
  'kikunojo': { gender: 'Female', affiliation: ['Kozuki Family'], firstArc: 'Wano' },
  'kozuki hiyori': { gender: 'Female', affiliation: ['Kozuki Family'], firstArc: 'Wano' },
  'kozuki momonosuke': { gender: 'Male', affiliation: ['Kozuki Family'], firstArc: 'Punk Hazard' },
  'krieg': { gender: 'Male' },                  // MAL: "Krieg" (Don Krieg)
  'kuro': { gender: 'Male' },
  'kurozumi kanjuro': { gender: 'Male', affiliation: ['Kurozumi Family'], firstArc: 'Dressrosa' },
  'lindbergh': { gender: 'Male' },
  'marguerite': { gender: 'Female' },
  'mont blanc cricket': { gender: 'Male', affiliation: ['Jaya'], firstArc: 'Jaya' },
  'mont blanc noland': { gender: 'Male', affiliation: ['Lvneel Kingdom'], firstArc: 'Skypiea' },
  'morgans': { gender: 'Male' },
  'morley': { gender: 'Male' },
  'nojiko': { gender: 'Female' },
  'oars': { gender: 'Male' },
  'ohm': { gender: 'Male' },
  'paulie': { gender: 'Male' },
  'pekoms': { gender: 'Male' },
  'pica': { gender: 'Male' },
  'queen': { gender: 'Male' },
  'raizou': { gender: 'Male', affiliation: ['Kozuki Family'], firstArc: 'Zou' },  // MAL: "Raizou"
  'scratchmen apoo': { gender: 'Male' },         // MAL: "Scratchmen, Apoo"
  'spandam': { gender: 'Male' },
  'urouge': { gender: 'Male' },
  'vegapunk': { gender: 'Male' },
  'vinsmoke judge': { gender: 'Male' },
  'viola': { gender: 'Female' },
  'wanda': { gender: 'Female' },
  'wyper': { gender: 'Male', affiliation: ['Shandia'], firstArc: 'Skypiea' },
  'x drake': { gender: 'Male' },                // MAL: "X, Drake" → key 'x drake'
  'zeff': { gender: 'Male' },
  'charlotte cracker': { gender: 'Male' },
  'charlotte daifuku': { gender: 'Male' },
  'charlotte oven': { gender: 'Male' },
  'curly dadan': { gender: 'Female' },          // MAL: "Curly, Dadan"
  'dellinger': { gender: 'Male' },
  'duval': { gender: 'Male' },
  'hannyabal': { gender: 'Male' },
  'helmeppo': { gender: 'Male' },
  'hina': { gender: 'Female' },
  'jaguar d saul': { gender: 'Male' },          // MAL: "Jaguar D., Saul"
  'jango': { gender: 'Male' },
  'kumadori': { gender: 'Male' },
  'leo': { gender: 'Male' },
  'lucky roux': { gender: 'Male' },             // MAL: "Lucky, Roux" → 'lucky roux'
  'makino': { gender: 'Female' },
  'portgas d rouge': { gender: 'Female' },
  'sadi': { gender: 'Female' },
  'sugar': { gender: 'Female' },
  'yasopp': { gender: 'Male' },
  'zeus': { gender: 'Male' },
  'shyarly': { gender: 'Female' },
  'stussy': { gender: 'Female' },
  'thatch': { gender: 'Male' },
  'vergo': { gender: 'Male' },
  'wapol': { gender: 'Male' },
  'nico olvia': { gender: 'Female' },           // MAL: "Nico, Olvia"
  'olvia nico': { gender: 'Female' },           // alternate key
  'inazuma': { gender: 'Male' },
  'corazon': { gender: 'Male' },                // Rosinante's alias key
  'boa marigold': { gender: 'Female' },
  'boa sandersonia': { gender: 'Female' },      // MAL: "Boa, Sandersonia"
  'sandersonia boa': { gender: 'Female' },      // alternate key
  'marigold boa': { gender: 'Female' },
  'nefertari cobra': { gender: 'Male' },
  'igaram': { gender: 'Male' },
  'vinsmoke ichiji': { gender: 'Male' },
  'vinsmoke niji': { gender: 'Male' },          // MAL: "Vinsmoke, Niji"
  'vinsmoke yonji': { gender: 'Male' },

  // ── Characters absent from bundle under expected name – full data ─────────
  'ashura doji': { gender: 'Male', affiliation: ['Wano Country'], firstArc: 'Wano' },
  'shutenmaru': { gender: 'Male', affiliation: ['Wano Country'], firstArc: 'Wano' },  // Ashura Doji alias
};
