// scripts/patch-wiki-ages.ts
// Targeted re-scrape: updates STATIC_WIKI_AGES for characters where the stored
// value is a pre-timeskip age (scraper bug took first semicolon-split value
// instead of last). Always overwrites the map entry regardless of existing value.
//
// Run: node_modules\.bin\tsx scripts/patch-wiki-ages.ts

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, '..');
const WIKI_API = 'https://onepiece.fandom.com/api.php';
const DELAY_MS = 1200;

// Characters known or suspected to have pre-timeskip ages in the static map.
// Format: [malName, wikiTitle] — wikiTitle is what the fandom wiki uses.
const TARGETS: [string, string][] = [
  ['Monkey D., Luffy',  'Monkey D. Luffy'],
  ['Nami',              'Nami'],
  ['Usopp',             'Usopp'],
  ['Roronoa, Zoro',     'Roronoa Zoro'],
  ['Sanji',             'Sanji'],
  ['Nico, Robin',       'Nico Robin'],
  ['Franky',            'Franky'],
  ['Brook',             'Brook'],
  ['Sabo',              'Sabo'],
  ['Koby',              'Koby'],
  ['Shanks',            'Shanks'],
  ['Nefertari, Vivi',   'Nefertari Vivi'],
  ['Jewelry Bonney',    'Jewelry Bonney'],
  ['Portgas D., Ace',   'Portgas D. Ace'],
];

const delay = (ms: number) => new Promise<void>((r) => setTimeout(r, ms));

function normalizeName(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9 ]/g, ' ').replace(/\s+/g, ' ').trim();
}

function cleanHtml(raw: string): string {
  return raw
    .replace(/<[^>]+>/g, ' ')
    .replace(/\[[\d,\s]+\]/g, '')
    .replace(/\s*;\s*/g, '; ')
    .replace(/\s+/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&#\d+;/g, '')
    .trim();
}

function extractField(html: string, field: string): string | null {
  const startIdx = html.indexOf(`data-source="${field}"`);
  if (startIdx < 0) return null;
  const valueStart = html.indexOf('pi-data-value', startIdx);
  if (valueStart < 0) return null;
  const openDiv = html.indexOf('>', valueStart) + 1;
  const closeDiv = html.indexOf('</div>', openDiv);
  if (closeDiv < 0) return null;
  return cleanHtml(html.substring(openDiv, closeDiv));
}

function processAge(raw: string): string | null {
  const clean = raw.replace(/\([^)]*\)/g, '').replace(/\s+/g, ' ').trim();
  // Ages may be semicolon-separated OR space-separated (wiki newline → space after HTML cleaning).
  // Either way, values are listed oldest→newest — take the last number found.
  const parts = clean.split(/;\s*/);
  const last = parts[parts.length - 1].trim();
  const nums = last.match(/\d+/g);
  if (nums) return nums[nums.length - 1];
  return null;
}

async function fetchAge(wikiTitle: string): Promise<string | null> {
  const params = new URLSearchParams({
    action: 'parse',
    page: wikiTitle,
    prop: 'text',
    format: 'json',
    formatversion: '2',
  });
  const res = await fetch(`${WIKI_API}?${params}`, {
    headers: { 'User-Agent': 'OmniWikiBot/1.0 (educational)' },
  });
  if (!res.ok) return null;
  const json = (await res.json()) as { error?: unknown; parse?: { text?: string } };
  if (json.error || !json.parse?.text) return null;
  const raw = extractField(json.parse.text, 'age');
  return raw ? processAge(raw) : null;
}

function loadExistingEntries(filePath: string): Record<string, string> {
  const result: Record<string, string> = {};
  if (!fs.existsSync(filePath)) return result;
  const content = fs.readFileSync(filePath, 'utf8');
  for (const m of content.matchAll(/'([^']+)':\s*'([^']+)'/g)) {
    result[m[1]] = m[2];
  }
  return result;
}

function writeAgesTs(filePath: string, data: Record<string, string>): void {
  const header =
    '// Auto-generated by scripts/scrape-wiki-meta.ts — do not edit by hand.\n' +
    '// Keys: normalizeName(character.name). Values: age from the One Piece wiki.';
  const entries = Object.entries(data)
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([k, v]) => `  '${k}': '${v}',`)
    .join('\n');
  fs.writeFileSync(filePath, `${header}\nexport const STATIC_WIKI_AGES: Record<string, string> = {\n${entries}\n};\n`, 'utf8');
}

async function main() {
  const agesPath = path.join(ROOT, 'src/lib/onepiece/static-wiki-ages.ts');
  const ages = loadExistingEntries(agesPath);

  console.log('Patching ages for known pre-timeskip entries...\n');

  for (const [malName, wikiTitle] of TARGETS) {
    const key = normalizeName(malName);
    const oldAge = ages[key] ?? '(none)';
    const newAge = await fetchAge(wikiTitle);
    await delay(DELAY_MS);

    if (newAge) {
      ages[key] = newAge;
      const changed = newAge !== oldAge;
      console.log(`${malName}: ${oldAge} → ${newAge}${changed ? '' : ' (unchanged)'}`);
    } else {
      console.log(`${malName}: fetch failed — keeping ${oldAge}`);
    }
  }

  writeAgesTs(agesPath, ages);
  console.log('\nWrote static-wiki-ages.ts');
}

main().catch(console.error);
